.test-job: &test-job
  image: $CI_JOB_NAME
  script:
    - rspec # prevent us from pushing to coveralls

ruby:2.2:
  <<: *test-job
ruby:2.3:
  <<: *test-job
ruby:2.4:
  <<: *test-job

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
